# -*- coding: utf-8 -*-
"""llm.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gymydyxoNxk3pMK8ySEFrZJ8Dk5qQIrE
"""


import openai
import os



openai.api_key  = 'sk-nURS6****'

def get_completion(prompt, model="gpt-3.5-turbo", temperature=0):
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=temperature,
    )
    return response.choices[0].message["content"]

data =[
    {
        "id":1,
        "Name": "Ayuda",
        "One_line": "Shelter for orphan children",
        "Description": "We need food, clothes, educational books, and any support for the lives of children. We're currently a team of 5, so volunteering is welcome.",
        "Need_Rating": 4,
        "Established_in": 2016,
        "State": "Tamil Nadu",
        "City": "Vellore"
    },
    {
        "id":2,
        "Name": "GreenFuture",
        "One_line": "Environmental conservation initiatives",
        "Description": "Focused on planting trees and cleaning rivers to protect the environment. Looking for donations of gardening tools, seeds, and volunteers for clean-up drives.",
        "Need_Rating": 3,
        "Established_in": 2012,
        "State": "Kerala",
        "City": "Kochi"
    },
    {
        "id":3,
        "Name": "EduBright",
        "One_line": "Promoting education in underprivileged areas",
        "Description": "We distribute educational materials and provide tutoring services. Need educational supplies, laptops, and volunteer teachers.",
        "Need_Rating": 5,
        "Established_in": 2018,
        "State": "Maharashtra",
        "City": "Pune"
    },
    {
        "id":4,
        "Name": "HealthAid",
        "One_line": "Healthcare services for the needy",
        "Description": "Offering free medical check-ups and treatments. We need medical supplies, drugs, and healthcare professionals to volunteer.",
        "Need_Rating": 4,
        "Established_in": 2015,
        "State": "West Bengal",
        "City": "Kolkata"
    },
    {
                "id":5,
        "Name": "AnimalGuard",
        "One_line": "Protection and care for homeless animals",
        "Description": "We rescue and shelter homeless animals. Looking for pet food, blankets, and volunteers for animal care.",
        "Need_Rating": 3,
        "Established_in": 2014,
        "State": "Gujarat",
        "City": "Ahmedabad"
    },
    {
                "id":6,

        "Name": "CultureConnect",
        "One_line": "Preserving indigenous cultures",
        "Description": "Promoting and preserving local cultures through workshops and events. Need art supplies, traditional costumes, and volunteers.",
        "Need_Rating": 2,
        "Established_in": 2017,
        "State": "Rajasthan",
        "City": "Jaipur"
    },
    {
                "id":7,

        "Name": "TechForGood",
        "One_line": "Bridging the digital divide",
        "Description": "Providing technology access and training to underprivileged communities. Need old laptops, tablets, and tech-savvy volunteers.",
        "Need_Rating": 5,
        "Established_in": 2019,
        "State": "Telangana",
        "City": "Hyderabad"
    },
    {
                "id":8,

        "Name": "FoodForAll",
        "One_line": "Fighting hunger with surplus food",
        "Description": "Collecting surplus food and distributing it to those in need. Looking for food donations and volunteers for distribution.",
        "Need_Rating": 4,
        "Established_in": 2013,
        "State": "Delhi",
        "City": "New Delhi"
    },
    {
                "id":9,

        "Name": "WaterWays",
        "One_line": "Ensuring clean water access",
        "Description": "Working on water purification projects and wells in rural areas. Need water filters, pipes, and volunteers for installations.",
        "Need_Rating": 3,
        "Established_in": 2011,
        "State": "Madhya Pradesh",
        "City": "Indore"
    },
    {
                "id":10,

        "Name": "SafeHaven",
        "One_line": "Support shelter for women in distress",
        "Description": "Providing shelter and support for women escaping violence. Looking for clothing, toiletries, and counselors or legal advisors to volunteer.",
        "Need_Rating": 5,
        "Established_in": 2020,
        "State": "Punjab",
        "City": "Chandigarh"
    }
]

# Extract and store the needed information in a structured format
extracted_data = {
    "Organizations": [{
        "Name": org["Name"],
        "Description": org["Description"],
        "Need_Rating": org["Need_Rating"],
        "State": org["State"],
        "City": org["City"]
    } for org in data]
}

extracted_data

user_details ={
"location": "Delhi",
}

few_shot=f"""
if user says i give clothes and food then
per word you have to search ngos like display ngos who
want food
then display all ngos that want food:
ayuda and foodforall ( display locationa  and need wise)
ngos who want clothes
then display all ngos that want clothing/clothes
: women rights and ayuda ( display locationa nd need wise)

Based on this return ngo names in a list sorted in location and need rating
output: [ women rights, ayuda, foodforall]
"""

context =f"""
Understand the context that goes into play here
if user says it wants to give clothes
it is likely that user wants to give human clothes
so suggest ngos that need clothes

if user specifies animal clothes because normally
a person who wants to donate wont be like i want to give
human clothes coz its natural to assume clothes mean human clothes
but if they mention animal in it then
you can say ok this is animal clothes and suggest ngos that need blankets or something for animals

"""

file_path_donation = './donation.txt'  # Adjust the file path as necessary

# Function to read text from the specified file
def read_from_donation_file(file_path):
    try:
        with open(file_path, 'r') as file:
            content = file.read()
            return content
    except FileNotFoundError:
        return "Donation file not found."

# Reading from the donation.txt file
donation_file_content = read_from_donation_file(file_path_donation)

donation_file_content

user_text = donation_file_content
prompt = f"""

I will give you a text and you have to apply similarity searching
and keyword based search understand the context of the text and then
go through the json i am providing { extracted_data}
And match the user's text and display ngo names whose description amtches
what the user wants keyword + context wise
then display results according to closest to user area
user's details are {user_details}
followed by need rating
{user_text}
dont assume what an ngo can do be very specific to the ngo description and thens ee context
so if ngo says it needs food and volunteers
user who gives clothes shoudlnt be suggested this ngo
if ngo says it wants clothes
then dont suggest that ngo to user willing to give food only.

with keyword search suggest all ngos whose description matches the user donation
not just one

Okay now analyze the user's text
This is an example
{few_shot}

Also keep the following context in consideration
while suggesting ngos {context}
Based on all info provided return a list of ngos that is based on ngo need and the nearest location to user
Prioritize 1. nearby location and then 2.needrating of ngos


Take into context and give answers
return a list [] of ngos sorted based on 1. location 2. need
If same location then look at need rating
otherwise first look at location
then look at need rating
Dont just return names of ngos return along with id s

like Ayuda(1), SafeHaven(10)

"""

response = get_completion(prompt)
print(response)

few ="""
1. "
User:
```I wnat to give clothes```


System :


```
Based on the user's text "I want to give clothes", we will first search for NGOs that specifically mention a need for clothes in their description.
User lives in Vellore

From the provided JSON data, the NGOs that mention a need for clothes are:
1. Women Rights - Located in Chandigarh, Punjab with a need rating of 5
2. Ayuda - Located in Vellore, Tamil Nadu with a need rating of 4

Since the user mentioned clothes, we will prioritize suggesting NGOs that specifically mention a need for clothes in their description.

Therefore, the suggested NGOs based on the user's donation of clothes, sorted by1.  location and 2. need rating, are:
1.  Ayuda
2. Women Rights

List : [Ayuda, Women Rights]
```
"
2.
"
User:
```  I want to give food nearby```

System :
```
Based on the user's text "I want to give food nearby", we will first analyze the keywords "food" and "nearby" to suggest NGOs that match the user's donation.
User lives in Vellore

Search for NGOs that need food:
   - Ayuda (Tamil Nadu, Vellore) - Need Rating: 4
   - FoodForAll (Delhi, New Delhi) - Need Rating: 4

Based on the context provided, we will prioritize suggesting Ayuda and FoodForAll to the user as they specifically mentioned wanting to give food. SafeHaven, which needs clothes, will not be suggested to the user in this case.

Therefore, the list of suggested NGOs based on 1. nearest location and 2. need rating to the user would be:
1. Ayuda
2. FoodForAll

List: [ Ayuda, FoodForAll]
"
"
3.
User:
```
I want to volunteer and give food
```
System:
```
Based on the user's text "I want to volunteer and give food", we will first analyze the keywords "volunteer" and "food" to suggest NGOs that match the user's donation intentions.
User lives in Vellore

1. NGOs that need food:
   - Ayuda (Vellore, Tamil Nadu) - Need Rating: 4
   - FoodForAll (New Delhi, Delhi) - Need Rating: 4

2. NGOs that need volunteers:
   - Ayuda (Vellore, Tamil Nadu) - Need Rating: 4
   - HealthAid (Kolkata, West Bengal) - Need Rating: 4
   - FoodForAll (New Delhi, Delhi) - Need Rating: 4

Based on the user's location in Vellore, Tamil Nadu, and the need for both food and volunteering, the suggested NGOs in order of priority would be:
1. Ayuda
2. FoodForAll

List:  [Ayuda, FoodForAll]
```
"
4.
User:
```
I want to volunteer and help people
```
System:
```
Based on the user's text "I want to volunteer and help people", we can analyze the keywords "volunteer" and "help people" to suggest NGOs that align with the user's intention.
User lives in Vellore

1. Search for NGOs that need volunteers:
- Ayuda: Needs volunteers, located in Vellore, Tamil Nadu, with a need rating of 4.
- EduBright: Needs volunteer teachers, located in Pune, Maharashtra, with a need rating of 5.
- HealthAid: Needs healthcare professionals to volunteer, located in Kolkata, West Bengal, with a need rating of 4.
- AnimalGuard: Needs volunteers for animal care, located in Ahmedabad, Gujarat, with a need rating of 3.
- SafeHaven: Needs counselors or legal advisors to volunteer, located in Chandigarh, Punjab, with a need rating of 5.

2. Search for NGOs that help people:
- Ayuda: Provides support for the lives of children, located in Vellore, Tamil Nadu, with a need rating of 4.
- HealthAid: Offers free medical check-ups and treatments, located in Kolkata, West Bengal, with a need rating of 4.
- SafeHaven: Provides shelter and support for women escaping violence, located in Chandigarh, Punjab, with a need rating of 5.

Based on the keyword search, the suggested NGOs for the user are Ayuda, HealthAid, and SafeHaven. These NGOs align with the user's intention to volunteer and help people. The list is sorted based on location and need rating, prioritizing nearby locations and higher need ratings.

List : [Ayuda, HealthAid, SafeHaven]
```
"
"
5.
User:
``` I am an animal lover and would love to contribute to something that helps animals!!
```
System:
```
Based on the user's text "I am an animal lover and would love to contribute to something that helps animals!!", we can identify the keywords "animal lover" and "helps animals".
User lives in Vellore
Using keyword-based search, we can match these keywords with the NGO descriptions to find relevant NGOs. In this case, the NGO "AnimalGuard" fits the user's criteria as it focuses on rescuing and sheltering homeless animals.

Next, we need to consider the context of the user's text. Since the user is interested in helping animals, we should prioritize NGOs that specifically mention the need for items related to animal care, such as pet food or blankets.

Based on the provided JSON data, the NGO "AnimalGuard" is the most suitable match for the user's criteria.

Therefore, the list of NGOs that match the user's criteria and are sorted based on location and need rating would be:
1. AnimalGuard (Gujarat, Ahmedabad) - Need Rating: 3

List:[AnimalGuard]
```
"
"""





prompt=f"""
From this response can you extract the list of ngos
that came as the result and
write their id in this format
[ NgoId1, ngoId2, ngoId3]
This is the response: {response}
"""
response1 = get_completion(prompt)
print(response1)

string_to_convert = response1
response1 = eval(string_to_convert)

# converted_list[0]

def get_ngos_by_ids_iterative(data, ids_list):
    result = []
    for id in ids_list:
        for ngo in data:
            if ngo["id"] == id:
                result.append(ngo)
                break  # Found the matching ID, no need to continue inner loop
    return result

# Example usage with the list [1, 8]

selected_ngos_iterative = get_ngos_by_ids_iterative(data, response1)


# Writing the result to a new file named data.js
with open('data.js', 'w') as file:
    file.write(f"const products = {selected_ngos_iterative}\n")
    file.write("export default products;")

selected_ngos_iterative